name: BadApple
version: '1.0-SNAPSHOT'
main: touhou.badapple.BadApple
api-version: 1.15
authors: [ LetsAllLoveLain ]
description: Playing Bad Apple on minecraft blocks
commands:
  badapple:
    description: 'Start playing Bad Apple on startblock position'
  setba:
    description: 'Save start block'

